# Gopkg.toml example

[[constraint]]
  version = "v1.1.1"
  name = "go.mongodb.org/mongo-driver"

[[constraint]]
  version = "v1.3.0"
  #branch = "mongo-driver"
  name = "github.com/simagix/keyhole"

[prune]
  go-tests = true
  unused-packages = true
