# Gopkg.toml example

[[constraint]]
  version = "v1.0.0"
  name = "go.mongodb.org/mongo-driver"

[[constraint]]
  version = "v1.1.0"
  name = "github.com/simagix/keyhole"

[prune]
  go-tests = true
  unused-packages = true
